name: Hello World on Push

on:
  push: # This triggers the workflow on any push event to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # This step checks out your repository's code

    - name: Echo Hello World
      run: echo "Hello, World!"